const eventData = [
        {
            id: 1,
            name: 'Yoga for Jorden - Morgenyoga & Morgenmad',
            date: '6/12/2025 - 10:00–11:30',
            image: 'images/yoga.jpg',
            title: 'Yoga for Jorden',
            description: 'Gratis yoga efterfulgt af morgenmad arrangeret af Den Grønne Ungdomsbevægelse Aarhus. Alle kan være med - ingen erfaring nødvendig. Et roligt fællesskab med fokus på kropslig omsorg, nærvær og bæredygtighed. NB: Først-til-mølle.',
            location: 'N. J. Fjords Gade 2, Aarhus C',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://forms.gle/X7yoNK7Jb7xpUh6UA',
            linkText: 'Tilmelding 6/12'
        },
        {
            id: 2,
            name: 'Repair Café Aarhus',
            date: '12/12/2025 - 12:30–15:30',
            image: 'images/repaircafe.jpg',
            title: 'Repair Café',
            description: 'Come by and repair your clothes, electronics, or bike with help from our team of volunteers! We\'re all about giving our belongings a second chance instead of throwing them away and buying new. It\'s free and we\'ve got the tools, but remember to bring your own spare parts. You can find us on the stairs at Dokk1 – every month ♻️🛠',
            location: 'Dokk1, 8000 Aarhus, Denmark',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://www.dokk1.dk',
            linkText: 'Se flere datoer'
        },
        {
            id: 3,
            name: 'INDENDØRS JuleMARKED - Vejlby-Risskov Hallen',
            date: '7/12/2025 - 10:00–16:00',
            image: 'images/market.jpg',
            title: 'Julemarked',
            description: 'Kom til det store juleloppemarked med 82 stande fyldt med julepynt, antik, legetøj, tøj og brugskunst. Her finder du gran, kogler, nisser, kalenderlys, kravlenisser, kugler, gløgg, æbleskiver og meget mere. Gør noget for klimaet - køb genbrug! Forventer ca. 3.000 besøgende.',
            location: 'Vejlby Centervej 51, 8240 Risskov',
            points: '+10 pts signup | +200 pts completion',
            link: 'mailto:kurt@kloborg.dk?subject=Tilmelding%20til%20Julemarked',
            linkText: 'Kontakt tilmelding'
        },
        {
            id: 4,
            name: 'Rå-hyggeligt Julemarked hos Hjerteland',
            date: '7/12/2025 - 12:00–17:00',
            image: 'images/market2.jpg',
            title: 'Julemarked',
            description: 'Kom til et hyggeligt julemarked i smukke omgivelser med duften af gløgg og æbleskiver. Find unikke julegaver som smykker, keramik, tøj, sko, naturlige cremer, malerier, drømmefangere, øjenpuder, håndværk i træ, honning, cookies, pebernødder og meget mere.',
            location: 'Nymøllevej 8, 8200 Aarhus N',
            points: '+10 pts signup | +200 pts completion',
            link: 'mailto:hjerteogko@live.dk?subject=Stand%20til%20Julemarked',
            linkText: 'Book stand'
        },
        {
            id: 5,
            name: 'Ananda Organics - Økologisk Hudpleje Lancering',
            date: '16/12/2025 - 16:30–18:00',
            image: 'images/health.png',
            title: 'Produktlancering',
            description: 'Kom og fejr lanceringen af Ananda Organics - certificeret økologisk hudpleje med 90-100% økologiske ingredienser. Få 30% rabat på luksuriøse ansigtsolier, fugtserum, mists, body butter, urtesalver og aromaterapi.',
            location: 'Hjerterum, Aarhus',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://www.annaananda.dk/',
            linkText: 'Besøg hjemmeside'
        },
        {
            id: 6,
            name: 'Community Gardening Workshop',
            date: '15/11/2025 - 10:00–14:00',
            image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80',
            title: 'Gardening Workshop',
            description: 'Learn sustainable gardening techniques and help maintain our community garden.',
            location: 'Aarhus Community Garden, 8000 Aarhus C',
            points: '+10 pts signup | +200 pts completion',
            link: '#',
            linkText: 'Event Ended'
        },
        {
            id: 7,
            name: 'Sustainable Cooking Class',
            date: '22/11/2025 - 17:00–20:00',
            image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80',
            title: 'Cooking Class',
            description: 'Learn how to cook delicious meals using locally sourced, sustainable ingredients.',
            location: 'Green Kitchen Aarhus, 8200 Aarhus N',
            points: '+10 pts signup | +200 pts completion',
            link: '#',
            linkText: 'Event Ended'
        },
        {
            id: 8,
            name: 'Beach Cleanup & Awareness',
            date: '29/11/2025 - 09:00–12:00',
            image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80',
            title: 'Beach Cleanup',
            description: 'Join us for a beach cleanup to protect our local marine environment.',
            location: 'Aarhus Beach, 8000 Aarhus C',
            points: '+10 pts signup | +200 pts completion',
            link: '#',
            linkText: 'Event Ended'
        },
        {
            id: 9,
            name: 'Plastic Reduction Workshop',
            date: '5/11/2025 - 13:00–16:00',
            image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?ixlib=rb-4.0.3&auto=format&fit=crop&w=2074&q=80',
            title: 'Plastic Workshop',
            description: 'Learn how to reduce plastic waste in your daily life with practical tips and alternatives.',
            location: 'Eco Center Aarhus, 8000 Aarhus C',
            points: '+10 pts signup | +200 pts completion',
            link: '#',
            linkText: 'Event Ended'
        },
        {
            id: 10,
            name: 'TirsdagsSpiren - Grønne aktiviteter i Aarhus',
            date: '20/1/2026 - 13:00–15:00',
            image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?ixlib=rb-4.0.3&auto=format&fit=crop&w=2074&q=80',
            title: 'TirsdagsSpiren',
            description: 'SPIS. DYRK. SKAB. Træd ind i vores grønne oase og bliv inspireret til et mere bæredygtigt liv. Vi er klar til både uformelle snakke og vilde idéer om grøn omstilling – og guider dig videre til grønne fællesskaber og aktiviteter på biblioteket.',
            location: 'Dokk1, Ved rulletrappen, niveau 1, 8000 Aarhus',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://www.dokk1.dk',
            linkText: 'Lær mere'
        },
        {
            id: 11,
            name: 'Plantekup - Botanisk Marked',
            date: '31/1/2026 - 10:00–16:30',
            image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80',
            title: 'Plantekup',
            description: 'Plantekup - et botanisk marked med masser af nedsatte priser på planter, keramik, design, vandegear til foråret og andet planteudstyr. Baren har som altid åbent, om du skal have en varm kakao eller frokosten med fadøl! 🙂',
            location: 'Plukk - Kjeld Tolstrups Gade 12, 8000 Aarhus',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://fb.me/e/6JghlmDDx',
            linkText: 'Facebook Event'
        },
        {
            id: 12,
            name: 'Tøjmaleri - Lav dit tøj om til kunst',
            date: '23/1/2026 - 16:00–18:00',
            image: 'images/tøj.jpg',
            title: 'Tøjmaleri Workshop',
            description: 'Få dit tøj lavet om til et unikt kunstværk! Kunstner Charlotte Moreno Kølkjær tilbyder at lave din gamle jakke, t-shirt eller sweatshirt om til et kunstværk. Kølkjær "maler" med klorin, der fjerner farven i tøjet præcist hvor det tilføjes, og efter et par sekunder dukker en smuk illustration op for dine øjne. Tøjet skal være 100% bomuld uden overfladebehandling. Alle andre farver end hvidt er egnet. Det er helt gratis - men på eget ansvar.',
            location: 'Kunst for alle, Vester Alle 1, 8000 Aarhus',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://fb.me/e/9lWjWnOfE',
            linkText: 'Facebook Event'
        },
        {
            id: 13,
            name: 'Tøjmaleri - Lav dit tøj om til kunst',
            date: '24/1/2026 - 15:00–17:00',
            image: 'images/tøj.jpg',
            title: 'Tøjmaleri Workshop',
            description: 'Få dit tøj lavet om til et unikt kunstværk! Kunstner Charlotte Moreno Kølkjær tilbyder at lave din gamle jakke, t-shirt eller sweatshirt om til et kunstværk. Kølkjær "maler" med klorin, der fjerner farven i tøjet præcist hvor det tilføjes, og efter et par sekunder dukker en smuk illustration op for dine øjne. Tøjet skal være 100% bomuld uden overfladebehandling. Alle andre farver end hvidt er egnet. Det er helt gratis - men på eget ansvar.',
            location: 'Kunst for alle, Vester Alle 1, 8000 Aarhus',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://fb.me/e/9lWjWnOfE',
            linkText: 'Facebook Event'
        },
        {
            id: 14,
            name: 'Tøjmaleri - Lav dit tøj om til kunst',
            date: '25/1/2026 - 11:00–13:00',
            image: 'images/tøj.jpg',
            title: 'Tøjmaleri Workshop',
            description: 'Få dit tøj lavet om til et unikt kunstværk! Kunstner Charlotte Moreno Kølkjær tilbyder at lave din gamle jakke, t-shirt eller sweatshirt om til et kunstværk. Kølkjær "maler" med klorin, der fjerner farven i tøjet præcist hvor det tilføjes, og efter et par sekunder dukker en smuk illustration op for dine øjne. Tøjet skal være 100% bomuld uden overfladebehandling. Alle andre farver end hvidt er egnet. Det er helt gratis - men på eget ansvar.',
            location: 'Kunst for alle, Vester Alle 1, 8000 Aarhus',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://fb.me/e/9lWjWnOfE',
            linkText: 'Facebook Event'
        },
        {
            id: 15,
            name: "Collage Workshop - One man's trash is this woman's treasure!",
            date: '8/2/2026 - 14:00–17:00',
            image: 'images/collage.png',
            title: 'Collage Workshop',
            description: 'Kom med til workshop med kunstner Marina Rubini Rordam aka Marina Scissorhands, hvis finurlige og detaljerige tankegang præger hendes tilgang til både kunst og liv. Kaffe/te og snacks er inkluderet. Begrænsede pladser – booking og betaling er påkrævet.',
            location: 'Rosenkrantzgade 22, baghuset, 8000 Aarhus',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://allevents.in/arhus/collage-workshop-one-mans-trash-is-this-womans-treasure/200029308050526',
            linkText: 'Event Info'
        },
        {
            id: 18,
            name: 'HÅNDVÆRK',
            date: '4/2/2026 - 09:00–17:00',
            image: 'images/håndværk.png',
            title: ' ',
            description: 'Vær med til årets fedeste festival, hvor vi hylder det gode håndværk og sætter fokus på flere spændende emner.',
            location: 'Aarhus',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://xn--hndvrk-iual.eu/',
            linkText: 'Event Info'
        },
        {
            id: 19,
            name: 'BEVARING & TRANSFORMATION',
            date: '16/3/2026 - 09:00–17:00',
            image: 'images/bevaring.png',
            title: ' ',
            description: 'Du får konkret viden om, hvorfor og hvornår det giver mening at transformere bygninger, og hvordan transformation kan bidrage til social revitalisering.',
            location: 'Aarhus',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://buildinggreen.eu/bevaringogtransformation/',
            linkText: 'Event Info'
        },
        {
            id: 20,
            name: 'BUILD FOR BIODIVERSITY',
            date: '24/3/2026 - 09:00–17:00',
            image: 'images/bio.png',
            title: ' ',
            description: 'Oplev en række dybt kompetente og inspirerende talere, der gennem oplæg og debatter gør dig klogere på urban biodiversitet.',
            location: 'Aarhus',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://www.buildinggreen.com/events',
            linkText: 'Event Info'
        },
        {
            id: 21,
            name: 'BG:VEST',
            date: '22/4/2026 - 09:00–17:00',
            image: 'images/bg.png',
            title: ' ',
            description: 'I løbet af 2 tætpakkede dage i Aarhus kan du opleve 4 faglige spor på 3 scener og en fyldt sal med spændende løsninger til byggeriet. Helt gratis!',
            location: 'Aarhus',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://buildinggreen.eu/bg-vest/',
            linkText: 'Event Info'
        },
        {
            id: 22,
            name: 'Planteværksted, karse og mikrogrønt',
            date: '16/2/2026 - 16:00–18:00',
            image: 'images/placeholder.png',
            title: 'Planteværksted, karse og mikrogrønt',
            description: 'Dyrk karse og andet mikrogrønt, dit eget fine grønne drys.',
            location: 'Hack Kampmanns Plads 2, Århus, DK 8000 (Dokk1, Aarhus)',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://dokk1.dk/alle-arrangementer',
            linkText: 'Event Info'
        },
        {
            id: 23,
            name: 'Frøbibliotek',
            date: '16/2/2026 - 16:00–18:00',
            image: 'images/placeholder.png',
            title: 'Frøbibliotek',
            description: 'Der findes frøbiblioteker på Dokk1 og flere lokalbiblioteker, med forskellige åbningstider. Åbningstiderne her gælder frøbiblioteket på Dokk1.',
            location: 'Hack Kampmanns Plads 2, Århus, DK 8000 (Dokk1, Aarhus)',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://dokk1.dk/alle-arrangementer',
            linkText: 'Event Info'
        },
        {
            id: 24,
            name: 'TirsdagsSpiren',
            date: '17/2/2026 - 13:00–15:00',
            image: 'images/placeholder.png',
            title: 'TirsdagsSpiren',
            description: 'SPIS. DYRK. SKAB. dig til et mere bæredygtigt liv i vores grønne oase.',
            location: 'Hack Kampmanns Plads 2, Århus, DK 8000 (Dokk1, Aarhus)',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://dokk1.dk/alle-arrangementer',
            linkText: 'Event Info'
        },
        {
            id: 25,
            name: 'TorsdagsSpiren',
            date: '19/2/2026 - 10:00–12:00',
            image: 'images/placeholder.png',
            title: 'TorsdagsSpiren',
            description: 'SPIS. DYRK. SKAB. dig til et mere bæredygtigt liv i vores lille grønne oase.',
            location: 'Hack Kampmanns Plads 2, Århus, DK 8000 (Dokk1, Aarhus)',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://dokk1.dk/alle-arrangementer',
            linkText: 'Event Info'
        },
        {
            id: 26,
            name: 'Billig bælgfrokost',
            date: '19/2/2026 - 11:30–12:00',
            image: 'images/placeholder.png',
            title: 'Billig bælgfrokost',
            description: 'SPIS dig til et mere bæredygtigt liv i vores lille grønne oase for kun 25 kr.',
            location: 'Hack Kampmanns Plads 2, Århus, DK 8000 (Dokk1, Aarhus)',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://dokk1.dk/alle-arrangementer',
            linkText: 'Event Info'
        },
        {
            id: 27,
            name: 'Frøbibliotek',
            date: '23/2/2026 - 16:00–18:00',
            image: 'images/placeholder.png',
            title: 'Frøbibliotek',
            description: 'Der findes frøbiblioteker på Dokk1 og flere lokalbiblioteker, med forskellige åbningstider. Åbningstiderne her gælder frøbiblioteket på Dokk1.',
            location: 'Hack Kampmanns Plads 2, Århus, DK 8000 (Dokk1, Aarhus)',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://dokk1.dk/alle-arrangementer',
            linkText: 'Event Info'
        },
        {
            id: 28,
            name: 'Planteværksted, karse og mikrogrønt',
            date: '23/2/2026 - 16:00–18:00',
            image: 'images/placeholder.png',
            title: 'Planteværksted, karse og mikrogrønt',
            description: 'Dyrk karse og andet mikrogrønt, dit eget fine grønne drys.',
            location: 'Hack Kampmanns Plads 2, Århus, DK 8000 (Dokk1, Aarhus)',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://dokk1.dk/alle-arrangementer',
            linkText: 'Event Info'
        },
        {
            id: 29,
            name: 'TirsdagsSpiren',
            date: '24/2/2026 - 13:00–15:00',
            image: 'images/placeholder.png',
            title: 'TirsdagsSpiren',
            description: 'SPIS. DYRK. SKAB. dig til et mere bæredygtigt liv i vores grønne oase.',
            location: 'Hack Kampmanns Plads 2, Århus, DK 8000 (Dokk1, Aarhus)',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://dokk1.dk/alle-arrangementer',
            linkText: 'Event Info'
        },
        {
            id: 30,
            name: 'TorsdagsSpiren',
            date: '26/2/2026 - 10:00–12:00',
            image: 'images/placeholder.png',
            title: 'TorsdagsSpiren',
            description: 'SPIS. DYRK. SKAB. dig til et mere bæredygtigt liv i vores lille grønne oase.',
            location: 'Hack Kampmanns Plads 2, Århus, DK 8000 (Dokk1, Aarhus)',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://dokk1.dk/alle-arrangementer',
            linkText: 'Event Info'
        },
        {
            id: 31,
            name: 'Vilde Vingede Væsner',
            date: '28/2/2026 - 13:00–14:30',
            image: 'images/placeholder.png',
            title: 'Vilde Vingede Væsner',
            description: 'Kom til gratis foredrag med Arternes Ambassadører, og hør om tre arter: mursejleren, gærdesmutten og strømfødt døgnflue.',
            location: 'Hack Kampmanns Plads 2, Århus, DK 8000 (Dokk1, Aarhus)',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://dokk1.dk/alle-arrangementer',
            linkText: 'Event Info'
        }
    ];