const eventData = [
        {
            id: 1,
            name: 'Yoga for the Earth - Morning Yoga & Breakfast',
            danishName: 'Yoga for Jorden - Morgenyoga & Morgenmad',
            date: '6/12/2025 - 10:00–11:30',
            image: 'images/yoga.jpg',
            title: 'Yoga for the Earth',
            danishTitle: 'Yoga for Jorden',
            description: 'Free yoga followed by breakfast organized by The Green Youth Movement Aarhus. Everyone can join - no experience necessary. A peaceful community with focus on physical care, mindfulness and sustainability. NB: First come, first served.',
            location: 'N. J. Fjords Gade 2, Aarhus C',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://forms.gle/X7yoNK7Jb7xpUh6UA',
            linkText: 'Sign up 6/12'
        },
        {
            id: 2,
            name: 'Repair Café Aarhus',
            danishName: 'Repair Café Aarhus',
            date: '12/12/2025 - 12:30–15:30',
            image: 'images/repaircafe.jpg',
            title: 'Repair Café',
            danishTitle: 'Repair Café',
            description: 'Come by and repair your clothes, electronics, or bike with help from our team of volunteers! We\'re all about giving our belongings a second chance instead of throwing them away and buying new. It\'s free and we\'ve got the tools, but remember to bring your own spare parts. You can find us on the stairs at Dokk1 – every month ♻️🛠',
            location: 'Dokk1, 8000 Aarhus, Denmark',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://www.dokk1.dk',
            linkText: 'See more dates'
        },
        {
            id: 3,
            name: 'INDOOR Christmas Market - Vejlby-Risskov Hall',
            danishName: 'INDENDØRS JuleMARKED - Vejlby-Risskov Hallen',
            date: '7/12/2025 - 10:00–16:00',
            image: 'images/market.jpg',
            title: 'Christmas Market',
            danishTitle: 'Julemarked',
            description: 'Come to the big Christmas flea market with 82 stalls filled with Christmas decorations, antiques, toys, clothing and crafts. Here you\'ll find trees, pine cones, elves, advent candles, elf figurines, ornaments, mulled wine, apple fritters and much more. Do something for the climate - buy secondhand! Expecting approx. 3,000 visitors.',
            location: 'Vejlby Centervej 51, 8240 Risskov',
            points: '+10 pts signup | +200 pts completion',
            link: 'mailto:kurt@kloborg.dk?subject=Tilmelding%20til%20Julemarked',
            linkText: 'Contact to register'
        },
        {
            id: 4,
            name: 'Cozy Christmas Market at Hjerteland',
            danishName: 'Rå-hyggeligt Julemarked hos Hjerteland',
            date: '7/12/2025 - 12:00–17:00',
            image: 'images/market2.jpg',
            title: 'Christmas Market',
            danishTitle: 'Julemarked',
            description: 'Come to a cozy Christmas market in beautiful surroundings with the scent of mulled wine and apple fritters. Find unique Christmas gifts like jewelry, ceramics, clothes, shoes, natural creams, paintings, dreamcatchers, eye pillows, woodwork, honey, cookies, gingerbread and much more.',
            location: 'Nymøllevej 8, 8200 Aarhus N',
            points: '+10 pts signup | +200 pts completion',
            link: 'mailto:hjerteogko@live.dk?subject=Stand%20til%20Julemarked',
            linkText: 'Book stand'
        },
        {
            id: 5,
            name: 'Ananda Organics - Organic Skincare Launch',
            danishName: 'Ananda Organics - Økologisk Hudpleje Lancering',
            date: '16/12/2025 - 16:30–18:00',
            image: 'images/health.png',
            title: 'Product Launch',
            danishTitle: 'Produktlancering',
            description: 'Come and celebrate the launch of Ananda Organics - certified organic skincare with 90-100% organic ingredients. Get 30% discount on luxurious face oils, moisture serums, mists, body butter, herbal salves and aromatherapy.',
            location: 'Hjerterum, Aarhus',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://www.annaananda.dk/',
            linkText: 'Visit website'
        },
        {
            id: 6,
            name: 'Community Gardening Workshop',
            danishName: 'Fælles Haveværksted',
            date: '15/11/2025 - 10:00–14:00',
            image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80',
            title: 'Gardening Workshop',
            danishTitle: 'Haveværksted',
            description: 'Learn sustainable gardening techniques and help maintain our community garden.',
            location: 'Aarhus Community Garden, 8000 Aarhus C',
            points: '+10 pts signup | +200 pts completion',
            link: '#',
            linkText: 'Event Ended'
        },
        {
            id: 7,
            name: 'Sustainable Cooking Class',
            danishName: 'Bæredygtigt Madlavningskursus',
            date: '22/11/2025 - 17:00–20:00',
            image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80',
            title: 'Cooking Class',
            danishTitle: 'Madlavningskursus',
            description: 'Learn how to cook delicious meals using locally sourced, sustainable ingredients.',
            location: 'Green Kitchen Aarhus, 8200 Aarhus N',
            points: '+10 pts signup | +200 pts completion',
            link: '#',
            linkText: 'Event Ended'
        },
        {
            id: 8,
            name: 'Beach Cleanup & Awareness',
            danishName: 'Strandrensning & Bevidsthed',
            date: '29/11/2025 - 09:00–12:00',
            image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80',
            title: 'Beach Cleanup',
            danishTitle: 'Strandrensning',
            description: 'Join us for a beach cleanup to protect our local marine environment.',
            location: 'Aarhus Beach, 8000 Aarhus C',
            points: '+10 pts signup | +200 pts completion',
            link: '#',
            linkText: 'Event Ended'
        },
        {
            id: 9,
            name: 'Plastic Reduction Workshop',
            danishName: 'Plastik Reduktions Workshop',
            date: '5/11/2025 - 13:00–16:00',
            image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?ixlib=rb-4.0.3&auto=format&fit=crop&w=2074&q=80',
            title: 'Plastic Workshop',
            danishTitle: 'Plastik Workshop',
            description: 'Learn how to reduce plastic waste in your daily life with practical tips and alternatives.',
            location: 'Eco Center Aarhus, 8000 Aarhus C',
            points: '+10 pts signup | +200 pts completion',
            link: '#',
            linkText: 'Event Ended'
        },
        {
            id: 10,
            name: 'Tuesday Sprout - Green Activities in Aarhus',
            danishName: 'TirsdagsSpiren - Grønne aktiviteter i Aarhus',
            date: '20/1/2026 - 13:00–15:00',
            image: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?ixlib=rb-4.0.3&auto=format&fit=crop&w=2074&q=80',
            title: 'Tuesday Sprout',
            danishTitle: 'TirsdagsSpiren',
            description: 'EAT. GROW. CREATE. Step into our green oasis and get inspired for a more sustainable life. We are ready for both informal chats and wild ideas about green transition – and we guide you to green communities and activities at the library.',
            location: 'Dokk1, By the escalator, level 1, 8000 Aarhus',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://www.dokk1.dk',
            linkText: 'Learn more'
        },
        {
            id: 11,
            name: 'Plant Deal - Botanical Market',
            danishName: 'Plantekup - Botanisk Marked',
            date: '31/1/2026 - 10:00–16:30',
            image: 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?ixlib=rb-4.0.3&auto=format&fit=crop&w=2070&q=80',
            title: 'Plant Deal',
            danishTitle: 'Plantekup',
            description: 'Plant Deal - a botanical market with lots of discounted prices on plants, ceramics, design, watering gear for spring and other plant equipment. The bar is open as always, whether you want a warm cocoa or lunch with draft beer! 🙂',
            location: 'Plukk - Kjeld Tolstrups Gade 12, 8000 Aarhus',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://fb.me/e/6JghlmDDx',
            linkText: 'Facebook Event'
        },
        {
            id: 12,
            name: 'Clothing Painting - Transform Your Clothes into Art',
            danishName: 'Tøjmaleri - Lav dit tøj om til kunst',
            date: '23/1/2026 - 16:00–18:00',
            image: 'images/tøj.jpg',
            title: 'Clothing Painting Workshop',
            danishTitle: 'Tøjmaleri Workshop',
            description: 'Get your clothes transformed into a unique artwork! Artist Charlotte Moreno Kølkjær offers to turn your old jacket, t-shirt or sweatshirt into an artwork. Kølkjær "paints" with chlorine, which removes the color precisely where it is applied, and after a few seconds a beautiful illustration appears before your eyes. Clothes must be 100% cotton without surface treatment. All colors except white are suitable. It\'s completely free - but at your own risk.',
            location: 'Kunst for alle, Vester Alle 1, 8000 Aarhus',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://fb.me/e/9lWjWnOfE',
            linkText: 'Facebook Event'
        },
        {
            id: 13,
            name: 'Clothing Painting - Transform Your Clothes into Art',
            danishName: 'Tøjmaleri - Lav dit tøj om til kunst',
            date: '24/1/2026 - 15:00–17:00',
            image: 'images/tøj.jpg',
            title: 'Clothing Painting Workshop',
            danishTitle: 'Tøjmaleri Workshop',
            description: 'Get your clothes transformed into a unique artwork! Artist Charlotte Moreno Kølkjær offers to turn your old jacket, t-shirt or sweatshirt into an artwork. Kølkjær "paints" with chlorine, which removes the color precisely where it is applied, and after a few seconds a beautiful illustration appears before your eyes. Clothes must be 100% cotton without surface treatment. All colors except white are suitable. It\'s completely free - but at your own risk.',
            location: 'Kunst for alle, Vester Alle 1, 8000 Aarhus',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://fb.me/e/9lWjWnOfE',
            linkText: 'Facebook Event'
        },
        {
            id: 14,
            name: 'Clothing Painting - Transform Your Clothes into Art',
            danishName: 'Tøjmaleri - Lav dit tøj om til kunst',
            date: '25/1/2026 - 11:00–13:00',
            image: 'images/tøj.jpg',
            title: 'Clothing Painting Workshop',
            danishTitle: 'Tøjmaleri Workshop',
            description: 'Get your clothes transformed into a unique artwork! Artist Charlotte Moreno Kølkjær offers to turn your old jacket, t-shirt or sweatshirt into an artwork. Kølkjær "paints" with chlorine, which removes the color precisely where it is applied, and after a few seconds a beautiful illustration appears before your eyes. Clothes must be 100% cotton without surface treatment. All colors except white are suitable. It\'s completely free - but at your own risk.',
            location: 'Kunst for alle, Vester Alle 1, 8000 Aarhus',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://fb.me/e/9lWjWnOfE',
            linkText: 'Facebook Event'
        },
        {
            id: 15,
            name: "Collage Workshop - One man's trash is this woman's treasure!",
            danishName: "Collage Workshop - One man's trash is this woman's treasure!",
            date: '8/2/2026 - 14:00–17:00',
            image: 'images/collage.png',
            title: 'Collage Workshop',
            danishTitle: 'Collage Workshop',
            description: 'Join a workshop with artist Marina Rubini Rordam aka Marina Scissorhands, whose clever and detailed mindset characterizes her approach to both art and life. Coffee/tea and snacks are included. Limited spaces – booking and payment required.',
            location: 'Rosenkrantzgade 22, baghuset, 8000 Aarhus',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://allevents.in/arhus/collage-workshop-one-mans-trash-is-this-womans-treasure/200029308050526',
            linkText: 'Event Info'
        },
        {
            id: 18,
            name: 'CRAFTWORK',
            danishName: 'HÅNDVÆRK',
            date: '4/2/2026 - 09:00–17:00',
            image: 'images/håndværk.png',
            title: 'Craftwork',
            danishTitle: 'HÅNDVÆRK',
            description: 'Join the year\'s coolest festival, where we celebrate good craftwork and focus on several exciting topics.',
            location: 'Aarhus',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://xn--hndvrk-iual.eu/',
            linkText: 'Event Info'
        },
        {
            id: 19,
            name: 'PRESERVATION & TRANSFORMATION',
            danishName: 'BEVARING & TRANSFORMATION',
            date: '16/3/2026 - 09:00–17:00',
            image: 'images/bevaring.png',
            title: 'Preservation & Transformation',
            danishTitle: 'BEVARING & TRANSFORMATION',
            description: 'You will gain concrete knowledge about why and when it makes sense to transform buildings, and how transformation can contribute to social revitalization.',
            location: 'Aarhus',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://buildinggreen.eu/bevaringogtransformation/',
            linkText: 'Event Info'
        },
        {
            id: 20,
            name: 'BUILD FOR BIODIVERSITY',
            danishName: 'BUILD FOR BIODIVERSITY',
            date: '24/3/2026 - 09:00–17:00',
            image: 'images/bio.png',
            title: 'Build for Biodiversity',
            danishTitle: 'BUILD FOR BIODIVERSITY',
            description: 'Experience a series of highly competent and inspiring speakers who, through presentations and debates, will make you wiser about urban biodiversity.',
            location: 'Aarhus',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://www.buildinggreen.com/events',
            linkText: 'Event Info'
        },
        {
            id: 21,
            name: 'BG:WEST',
            danishName: 'BG:VEST',
            date: '22/4/2026 - 09:00–17:00',
            image: 'images/bg.png',
            title: 'BG:West',
            danishTitle: 'BG:VEST',
            description: 'During 2 packed days in Aarhus, you can experience 4 professional tracks on 3 stages and a full hall with exciting solutions for construction. Completely free!',
            location: 'Aarhus',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://buildinggreen.eu/bg-vest/',
            linkText: 'Event Info'
        },
        {
            id: 22,
            name: 'Plant Workshop, Cress and Microgreens',
            danishName: 'Planteværksted, karse og mikrogrønt',
            date: '16/2/2026 - 16:00–18:00',
            image: 'images/placeholder.png',
            title: 'Plant Workshop, Cress and Microgreens',
            danishTitle: 'Planteværksted, karse og mikrogrønt',
            description: 'Grow cress and other microgreens, your own fine green sprinkle.',
            location: 'Hack Kampmanns Plads 2, Århus, DK 8000 (Dokk1, Aarhus)',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://dokk1.dk/alle-arrangementer',
            linkText: 'Event Info'
        },
        {
            id: 23,
            name: 'Seed Library',
            danishName: 'Frøbibliotek',
            date: '16/2/2026 - 16:00–18:00',
            image: 'images/placeholder.png',
            title: 'Seed Library',
            danishTitle: 'Frøbibliotek',
            description: 'There are seed libraries at Dokk1 and several local libraries, with different opening hours. The opening hours here apply to the seed library at Dokk1.',
            location: 'Hack Kampmanns Plads 2, Århus, DK 8000 (Dokk1, Aarhus)',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://dokk1.dk/alle-arrangementer',
            linkText: 'Event Info'
        },
        {
            id: 24,
            name: 'Tuesday Sprout',
            danishName: 'TirsdagsSpiren',
            date: '17/2/2026 - 13:00–15:00',
            image: 'images/placeholder.png',
            title: 'Tuesday Sprout',
            danishTitle: 'TirsdagsSpiren',
            description: 'EAT. GROW. CREATE. yourself to a more sustainable life in our green oasis.',
            location: 'Hack Kampmanns Plads 2, Århus, DK 8000 (Dokk1, Aarhus)',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://dokk1.dk/alle-arrangementer',
            linkText: 'Event Info'
        },
        {
            id: 25,
            name: 'Thursday Sprout',
            danishName: 'TorsdagsSpiren',
            date: '19/2/2026 - 10:00–12:00',
            image: 'images/placeholder.png',
            title: 'Thursday Sprout',
            danishTitle: 'TorsdagsSpiren',
            description: 'EAT. GROW. CREATE. yourself to a more sustainable life in our little green oasis.',
            location: 'Hack Kampmanns Plads 2, Århus, DK 8000 (Dokk1, Aarhus)',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://dokk1.dk/alle-arrangementer',
            linkText: 'Event Info'
        },
        {
            id: 26,
            name: 'Cheap Legume Lunch',
            danishName: 'Billig bælgfrokost',
            date: '19/2/2026 - 11:30–12:00',
            image: 'images/placeholder.png',
            title: 'Cheap Legume Lunch',
            danishTitle: 'Billig bælgfrokost',
            description: 'EAT yourself to a more sustainable life in our little green oasis for only 25 kr.',
            location: 'Hack Kampmanns Plads 2, Århus, DK 8000 (Dokk1, Aarhus)',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://dokk1.dk/alle-arrangementer',
            linkText: 'Event Info'
        },
        {
            id: 27,
            name: 'Seed Library',
            danishName: 'Frøbibliotek',
            date: '23/2/2026 - 16:00–18:00',
            image: 'images/placeholder.png',
            title: 'Seed Library',
            danishTitle: 'Frøbibliotek',
            description: 'There are seed libraries at Dokk1 and several local libraries, with different opening hours. The opening hours here apply to the seed library at Dokk1.',
            location: 'Hack Kampmanns Plads 2, Århus, DK 8000 (Dokk1, Aarhus)',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://dokk1.dk/alle-arrangementer',
            linkText: 'Event Info'
        },
        {
            id: 28,
            name: 'Plant Workshop, Cress and Microgreens',
            danishName: 'Planteværksted, karse og mikrogrønt',
            date: '23/2/2026 - 16:00–18:00',
            image: 'images/placeholder.png',
            title: 'Plant Workshop, Cress and Microgreens',
            danishTitle: 'Planteværksted, karse og mikrogrønt',
            description: 'Grow cress and other microgreens, your own fine green sprinkle.',
            location: 'Hack Kampmanns Plads 2, Århus, DK 8000 (Dokk1, Aarhus)',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://dokk1.dk/alle-arrangementer',
            linkText: 'Event Info'
        },
        {
            id: 29,
            name: 'Tuesday Sprout',
            danishName: 'TirsdagsSpiren',
            date: '24/2/2026 - 13:00–15:00',
            image: 'images/placeholder.png',
            title: 'Tuesday Sprout',
            danishTitle: 'TirsdagsSpiren',
            description: 'EAT. GROW. CREATE. yourself to a more sustainable life in our green oasis.',
            location: 'Hack Kampmanns Plads 2, Århus, DK 8000 (Dokk1, Aarhus)',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://dokk1.dk/alle-arrangementer',
            linkText: 'Event Info'
        },
        {
            id: 30,
            name: 'Thursday Sprout',
            danishName: 'TorsdagsSpiren',
            date: '26/2/2026 - 10:00–12:00',
            image: 'images/placeholder.png',
            title: 'Thursday Sprout',
            danishTitle: 'TorsdagsSpiren',
            description: 'EAT. GROW. CREATE. yourself to a more sustainable life in our little green oasis.',
            location: 'Hack Kampmanns Plads 2, Århus, DK 8000 (Dokk1, Aarhus)',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://dokk1.dk/alle-arrangementer',
            linkText: 'Event Info'
        },
        {
            id: 31,
            name: 'Wild Winged Creatures',
            danishName: 'Vilde Vingede Væsner',
            date: '28/2/2026 - 13:00–14:30',
            image: 'images/placeholder.png',
            title: 'Wild Winged Creatures',
            danishTitle: 'Vilde Vingede Væsner',
            description: 'Come to a free lecture with the Species Ambassadors, and hear about three species: the swift, the wren and the stream mayfly.',
            location: 'Hack Kampmanns Plads 2, Århus, DK 8000 (Dokk1, Aarhus)',
            points: '+10 pts signup | +200 pts completion',
            link: 'https://dokk1.dk/alle-arrangementer',
            linkText: 'Event Info'
        }
    ];